### ISSUE TITLE
Editing a template parameter should update all implementors who did not override it

### ISSUE THREAD

**Issue by drekbour** [JoelJ/ez-templates#14]
I have generally come to expect (mostly from TeamCity) that if you do not specify an override to a parameter then it should track any changes in the template.

* In ez-templates we do not have an explicit "inherit" checkbox next to a field to signify this clearly so the assumption would be that an unchanged parameter means "inherit".
* In all cases, a changed parameter will never be updated.

**Comment by kenorb** [comment]
I guess this is fixed in 1.2.2, see: [JENKINS-37399](https://issues.jenkins-ci.org/browse/JENKINS-37399)

**Comment by drekbour** [comment]
This github project is defunct and should be deleted. I can't do that but can close all these issues.

Regards _this_ item, it's still a good idea but EZ doesn't have three sources to merge so doesn't know that the template changed it's setting - all it sees is that they are different (so looks exactly the same as if the child has changed it's default).
