### ISSUE TITLE
Make html inputs "readonly" when configuring implemented job

### ISSUE THREAD

**Issue by Brantone** [JoelJ/ez-templates#26]
This is another "not sure how hard it is, hope it's easy" type enhancement ... 

When configuring an implemented job, have all the "non-editable" fiels actually be readonly (in HTML). Would be good way to enforce/remind user that fields can't actually be changed since will be overwritten by template.

I have a sense this is harder than I hoped in straight HTML, so possibly post-page load in Javascript by traversing the JS DOM ?

**Comment by Brantone** [comment]
Would be a cross-over with the "read only" plugin (ex: https://wiki.jenkins-ci.org/display/JENKINS/Read-only+configurations+plugin + http://wiki.hudson-ci.org/display/HUDSON/Extended+Read+Permission+Plugin)

**Comment by drekbour** [comment]
Am closing this one as "not viable" given the current framework. There isn't an easily discerned mapping from config.xml through all those Jelly tags to the UI widgets. Some might be quite direct - some might bind directly to an Xml property but others could be entirely hidden in some plugin's source code.

**Comment by Brantone** [comment]
Understandable. Thx
