### ISSUE TITLE
Support for template parameters, as well as job parameters

### ISSUE THREAD

**Issue by aritzbastida** [JoelJ/ez-templates#30]
I have just tried out ez-templates, which seems a very interesting solution to reduce the maintainance nightmare in big Jenkins installs (with lots of similar jobs doing the same thing, but needing a private workspace).

As far as I know, the only way to parameterize each job (template instance) based on a template, is by creating a full-blown Job Parameter ("This build is parameterized"). However, this will not always be desirable. For example, we may want to define a sample "build" job, which compiles and tests our project, and send an email notification to the development team if it fails.

Ok, so we can define a "template_build" job, and define two parameters: "REPO_URL" and "NOTIFY_TO".

Now we can make several instances of it and, for each job (development project), specify the SCM Url (e.g. "http://example.com/svn/project/trunk") and notification addresses (e.g. "developerA@example.com, teamLead@example.com")

However, now it will be a bit awkward to execute this Build, because now it is a "Build with Parameters". Some plugins or scripts may not work with it the same way (the REST interface is different now), and more importantly, we have a form now to modify these data each time we execute the build. So, a user with the rights to execute the build, can essentially also configure it (because he can change the REPO_URL and NOTIFY_TO values, which should be hidden in the configuration).

Moreover, we may have also first-level Job Parameters, which are not intertwined with these template parameters. 

So, the question is: is there some way to defined template parameters I am missing here? If not, I would propose to add support for template parameters. I think that in a previous effort of JoelJ, there was such a feature ("Templating" repo).

Thank you in advance for considering this!

Regards,
Aritz

**Comment by JoelJ** [comment]
@aritzbastida Sorry for the delayed response. My first implementation was fragile. I'm sure revisiting that type of templating wouldn't be a waste of time, but I'm not sure if that should be the goal of this plugin. I really like the simplicity. It uses existing Jenkins parameter expansion, so it works with any plugin that supports that. However, I wouldn't be completely opposed to adding something like this into this plugin for power-users. I'll take a look at your PR.

**Comment by aritzbastida** [comment]
Hi @Joel! Thanks for taking a look at my PR, and conside. I think that the proposed implementation of template parameters is also simple (yet effective), and provides clear added-value when plain-old Jenkins job parameters are not convenient. But, of course, I am not neutral :stuck_out_tongue:
