### ISSUE TITLE
Support for Promoted Builds plugin

### ISSUE THREAD

**Issue by Brantone** [JoelJ/ez-templates#31]
Would be sweet to also have support for promoted builds plugin ... 
In my current setup, it's actually part of the <properties> section, as "<hudson.plugins.promoted__builds.JobPropertyImpl plugin="promoted-builds@2.19">" , it contains a string reference to the promotion job, which then has a folder + config.xml setup of it's own (since it's similar to another job, just nested) ...

So probably more complex than originally hoped :(

**Comment by philipmattingly** [comment]
+1 for the syncing of the Promote Build jobs.. currently have to edit the template promote config.. then copy the file on disk to all the builds sub dirs and reload from files.

**Comment by drekbour** [comment]
Looks like a good plugin, I'll take a look (next month!).

**Comment by flashvoid** [comment]
+1 Would be really great.

**Comment by juanpablo-santos** [comment]
Apologies on not sending an appropiate PR, but the code needed is really small (don't know Jenkins internals on detail, so the code may have room for improvement):

First, you'll need to add the following dependency to the `pom.xml` file:
```xml
    <dependency>
      <groupId>org.jenkins-ci.plugins</groupId>
      <artifactId>promoted-builds</artifactId>
      <version>2.21</version>
    </dependency>
```

Then, on `TemplateUtils#handleTemplateImplementationSaved`, at the end of the method, just before the call to `ProjectUtils.silentSave(implementationProject);`, add the following piece of code:

```java
final JobPropertyImpl promotion = ( JobPropertyImpl )implementationProject.getProperty( JobPropertyImpl.class );
if( promotion != null ) {
    LOG.info( String.format("Found [%s].", promotion.getFullDisplayName() ) );

    LOG.info( String.format( "Removing existing promotions at [%s].", implementationProject.getFullDisplayName() ) );
    implementationProject.removeProperty( JobPropertyImpl.class );
    Util.deleteRecursive( new File( implementationProject.getRootDir(), "promotions" ) );
    promotion.getItems().clear();

    LOG.info( String.format( "Recreate promotions for [%s].", implementationProject.getFullDisplayName() ) );
    final File templatePromotions = new File( templateProject.getRootDir(),"promotions" );
    final String[] list = templatePromotions.list();
    if( list != null ) {
        for( final String promotionDir : list ) {
            final File templatePromotionProcess = new File( templatePromotions, promotionDir );
            if( templatePromotionProcess.isDirectory() ) {
                File templatePromotionConfigXml = new File( templatePromotionProcess, "config.xml" );
                promotion.createProcessFromXml( promotionDir, 
                                                new FileInputStream( templatePromotionConfigXml ) );
            }
        }
    }

    implementationProject.addProperty( promotion );
}
```
(you'll need to add `import hudson.plugins.promoted_builds.JobPropertyImpl;` to this class too)

WDYT?

**Comment by drekbour** [comment]
Done six months ago :)

**Comment by emoshaya** [comment]
Can someone please explain step by step how to sync promotions from a mater template with the child jobs? Do you use the original jobs as the template? Or do you edit the config for the promotion and use as a template? What next? Do you need to copy config files across all child templates? Even with the https://github.com/juanpablo-santos/ez-templates/commit/7d377c4f3c454769f97b4a5e821abd78e56cd4b1 commit supporting the plugin?

I raised this issue https://github.com/JoelJ/ez-templates/issues/60 as I cannot for the life of me get the promoted builds plugin to work with ez templates plugin.
