### ISSUE TITLE
Publish EZ-Templates on main Jenkins Plugin site

### ISSUE THREAD

**Issue by jbarmash** [JoelJ/ez-templates#41]
I found it and installed it today - I think it's great, but not being available in the main plugin repository is a barrier to discoverability.

**Comment by JoelJ** [comment]
It's been a while since last time I've done this. So hopefully I gave them enough info (I can't seem to find the documentation on the proper way to do this anymore :/ )

https://groups.google.com/forum/#!topic/jenkinsci-dev/NVLHCFegfYw

I'll close this when it goes public!

**Comment by tomkuijsten** [comment]
This looks promising, would be nice to be available in the plugin repository. In the meanwhile, could you add a compiled version to download? Or add some more details how to get this installed on Jenkins?

**Comment by JohnMurray** [comment]
@tomkuijsten - You can download the `.hpi` files [on the releases page](https://github.com/JoelJ/ez-templates/releases).

**Comment by Brantone** [comment]
I think they're waiting on response to:
https://groups.google.com/d/msg/jenkinsci-dev/NVLHCFegfYw/pEiNh1Brc4sJ

**Comment by lkraider** [comment]
How does this plugin differ from https://wiki.jenkins-ci.org/display/JENKINS/Template+Project+Plugin ?

**Comment by Brantone** [comment]
For one, template-project doesn't deal with parameters, but beyond that there are quite a few other difference. Think of template-project as a means to "stack pieces onto a job" ... whereas ez-template is actually a full-on template that gets implemented by other jobs.

**Comment by lkraider** [comment]
Thanks, it seems exactly what I need. I'll build it and give it try. Also, I noticed it is available in the jenkins-ci git but not on the install/wiki pages. Is there anything we can do to help it get in?

**Comment by Brantone** [comment]
@JoelJ ^^ ? I can lend a hand if it helps.

**Comment by ixdy** [comment]
Any update here? This plugin would be very helpful to us.

**Comment by drekbour** [comment]
Not sure where this got to, I can see ez was forked in to the jenkins-ci group. I'm not sure if I like that or not :) So long as I don't *have* to use JIRA to manage bugs for code in Github, I'm happy.

I will chase up this up and try to finish the job.

**Comment by JoelJ** [comment]
Sorry for the radio silence everyone. My personal life has become very busy, and I don't spend nearly as much time in Jenkins like I used to.

Looks like @drekbour is taking this over the finish line. Thanks!

**Comment by drekbour** [comment]
Done.
https://github.com/jenkinsci/ez-templates-plugin
https://wiki.jenkins-ci.org/display/JENKINS/EZ+Templates+Plugin

@joelj, Can you shut down the Issues and Pulls. I'll commit a replacement README.MD to redirect users.

**Comment by emoshaya** [comment]
@drekbour replacement README.MD would be nice to get more contributors..

**Comment by drekbour** [comment]
The replacement I meant was committed to _this_ repo to stop people raising issues here since Joel hasn't closed it down yet: https://github.com/JoelJ/ez-templates/
Jenkins admins insist we should be using their JIRA for support tickets and not GH issues (not sure I agree with this myself for the case of non-core plugins like this).

**Comment by drekbour** [comment]
@joelj Can you close this repo (or at least disable the issues pages so we redirect to the new home). I would [request GH support](https://github.com/contact) to set up a [redirect](https://github.com/blog/1508-repository-redirects-are-here) to https://github.com/jenkinsci/ez-templates-plugin
