### ISSUE TITLE
New checkbox for "Ownership" plugin

### ISSUE THREAD

**Issue by Brantone** [JoelJ/ez-templates#43]
Similar to SCM and Security Permissions checkboxes, looking to do same for Ownership plugin.

Brings up side issue of configuring for various other plugins could get into many other options.

**Comment by drekbour** [comment]
We need to add some help/tooltips to these checkboxes before adding yet more.

**Comment by Brantone** [comment]
Agreed, that list has bad potential to become unruly ... I've been trying to think of a way to make it more streamlined and intuitive, maybe text input with defined options that auto-complete (like the "Component" list in Jira).
