### ISSUE TITLE
Have build trigger with git webhooks

### ISSUE THREAD

**Issue by swestner** [JoelJ/ez-templates#45]
When a git hook is defined in the parent project, in the jenkins log you can see the webhook register and jenkins recieve the POST, but the project is not poked, and no build is triggered.

os : windows server 2012
jenkins : 1.607

**Comment by drekbour** [comment]
Do you mean this: https://wiki.jenkins-ci.org/display/JENKINS/Git+Plugin#GitPlugin-Pushnotificationfromrepository

I'll need a slightly more detailed usecase to do anything with this issue as it doesn't currently sound like it's even related to ez-templates!
