### ISSUE TITLE
This plugin is not hosted at the community repo at jenkins-ci.org

### ISSUE THREAD

**Issue by wickedH** [JoelJ/ez-templates#49]
Is there a reason that you are not hosting this plugin in the community plugin repository?  https://wiki.jenkins-ci.org/display/JENKINS/Hosting+Plugins

**Comment by OscarBarrett** [comment]
See:
https://github.com/JoelJ/ez-templates/issues/41
https://groups.google.com/forum/#!topic/jenkinsci-dev/NVLHCFegfYw

**Comment by wickedH** [comment]
Duplicate of #41
