### ISSUE TITLE
Allow to disable synchronization for "Label Expression"

### ISSUE THREAD

**Issue by jet47** [JoelJ/ez-templates#50]
It would be nice to have option to disable synchronization of "Restrict where this project can be run" and "Label Expression" project properties.

**Comment by Brantone** [comment]
I can understand some of the other sync disabling, but wouldn't disabling label expression defeat the purpose of similar builds running in a similar manner? 
As a potential work-around, what about using something like https://wiki.jenkins-ci.org/display/JENKINS/Groovy+Label+Assignment+plugin ?

**Comment by drekbour** [comment]
I used https://wiki.jenkins-ci.org/display/JENKINS/NodeLabel+Parameter+Plugin to achieve this without changing ez-templates

**Comment by jet47** [comment]
> I can understand some of the other sync disabling, but wouldn't disabling label expression defeat the purpose of similar builds running in a similar manner? 

For example, we can have one build and test configuration for different OS versions. To distinguish builds for different OS I use different jobs, that's why I would like to disable synchronization for "Assgined Labels".

> I used https://wiki.jenkins-ci.org/display/JENKINS/NodeLabel+Parameter+Plugin to achieve this without changing ez-templates

Yes, it works. The only drawback of the NodeLabel plugin is that it doesn't allow to see Jobs tied to specific node or label.

I submitted a PR for this feature : https://github.com/JoelJ/ez-templates/pull/51

**Comment by drekbour** [comment]
On consideration, this one is simple enough to merge. It should still be noted that it can be worked around with NodeLabel.
