### ISSUE TITLE
Support for additional Build Steps in Implementation Job

### ISSUE THREAD

**Issue by arpitgold** [JoelJ/ez-templates#52]
Hi,

I want to configure my jobs in such a way that I can add some additional(extra build steps which is not  there in template job) build or post build step in my implementation job but when I save the job, all additional step got overridden by template job. And there are only steps which are present in template job 

I want to configure my  job as follows :

In Template Project there are:
 
- Some Build Steps
- Some Post Build Steps

And In Implementation Job I want

- All the Build Steps and Post Build Steps of template job
- additionally I want some more Build step and post build steps

Can you please suggest. How can I do this.

**Comment by OscarBarrett** [comment]
You could use a plugin like [conditional buildstep](https://wiki.jenkins-ci.org/display/JENKINS/Conditional+BuildStep+Plugin) to have all steps in the template but only trigger the ones you need for each build.

**Comment by arpitgold** [comment]
Hi @OscarBarrett ,

We have too many jobs which are not related to each other, but there job structure is same. By using Conditional Plugin in Template job, Implementation job will have unnecessary jobs which are not related to current jobs as template plugin has all the jobs because of multijob plugin.

Can we create a functionality which is similar to conditional plugin holds build steps.

We can create template build step container and implementation build step container. And implementation build step will be used as is implemented in implementation job.

![](http://i.imgur.com/FGW9SRc.png)

It will be great functionality to use ez-Template as a Template plugin.

**Comment by arpitgold** [comment]
Any update on this ??
