### ISSUE TITLE
Allow disabling sync of publishers 

### ISSUE THREAD

**Issue by PaulRoffel** [JoelJ/ez-templates#57]
I have a divergence between 2 types of builds running from the same template:
* Most of them I don't want to send out post-build emails
* Some of them I do (special build cases)

The only difference is the <publishers> section of the config (Post-build Actions).
Please add a Sync Option that permits this divergence.

**Comment by drekbour** [comment]
I use
https://wiki.jenkins-ci.org/display/JENKINS/Conditional+BuildStep+Plugin
https://wiki.jenkins-ci.org/display/JENKINS/Flexible+Publish+Plugin
to allows template implementations to handle similar requirements. Have you looked at those? The second one combined with a job-parameter like EMAIL_ADDR should do what you want.

**Comment by PaulRoffel** [comment]
Thank you for the reply, and the ideas.

Unfortunately, there are incompatibilities with both of those plugins that make them "difficult" to use in our case.
* Conditional Build Steps
** Doesn't work with python (the step type doesn't show up at all)
** If using build flow, you have to run the groovy file outside of the Jenkins sandbox, and you need groovy installed on all of the clients you're planning on running the jobs on.
* Flexible Publish Plugin
** Doesn't work "well" with Build Pipeline, Post Build Task, nor warnings, all of which are in use in our current incarnation.

I'd much rather have a smaller amount of plugins in use, but our requirements are pretty high.
Would it be possible to add an option to allow child jobs to control their publishing steps individually?

**Comment by tof1a** [comment]
+1 We would also need to allow child jobs to control their publishing steps individually?
Thanks a lot in advance...

**Comment by drekbour** [comment]
See links to two plugins allowing you to control those from job properties. 
FYI: This GH project is the defunct predecessor of the current plugin. Any requests should be made through the JENKINS jira site!
