### ISSUE TITLE
Error when saving template

### ISSUE THREAD

**Issue by emoshaya** [JoelJ/ez-templates#59]
When applying a change to a template, I get a white screen. the change is then a hit and miss. Sometimes the inheriting jobs update with the change, sometimes they don't. I always have to double check a child job. I've noticed this with a large number of jobs using the same template... We have 30+ using the same template.

![screenshot](https://cloud.githubusercontent.com/assets/8818542/12946568/686a6550-cfed-11e5-8447-f40d84623cc6.png)

**Comment by drekbour** [comment]
Hi
This project is defunct, hosting is now elsewhere.
https://wiki.jenkins-ci.org/display/JENKINS/EZ+Templates+Plugin

Please report via http://issues.jenkins-ci.org/secure/IssueNavigator.jspa?mode=hide&reset=true&jqlQuery=project+%3D+JENKINS+AND+status+in+%28Open%2C+%22In+Progress%22%2C+Reopened%29+AND+component+%3D+%27ez-templates-plugin%27

:) + include any relvant snippet of your jenkins logs as I can't do much without some kind of stack trace and your server version.
