### ISSUE TITLE
Promoted Builds Plugin Not Syncing.

### ISSUE THREAD

**Issue by emoshaya** [JoelJ/ez-templates#60]
I am using:
2.26 of the promoted builds plugin
Jenkins ver. 1.656
1.1.2 EZ Templates

For some reason when I add a promotion to the template job, The jobs inheriting this template does not have the promotion. How to you sync the promotions with the template job?

**Comment by drekbour** [comment]
1) I checked this recently actually although i didn't try adding a promotion after templating. Promotions are seperate config.xml files. EZ pretty much just just copies them from the template
Code in question is here: https://github.com/jenkinsci/ez-templates-plugin/blob/master/src/main/java/com/joelj/jenkins/eztemplates/promotedbuilds/PromotedBuildsTemplateUtils.java

2) This is not the repo for this plugin any more. Anything further needs to be raised (perhaps with a supporting piece of jenkins log in this case) here:
https://issues.jenkins-ci.org/browse/JENKINS-32267?jql=project%20%3D%20JENKINS%20AND%20status%20in%20%28Open%2C%20%22In%20Progress%22%2C%20Reopened%29%20AND%20component%20%3D%20%27ez-templates-plugin%27

(i know it's not as nice as GH by a long way)
